name: Lint, Test, Deploy
on: push
jobs: 
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Signal lint start
        run: echo "linting app..."
      - name: Run linting script
        run: npm run lint
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Signal test start
        run: echo "testing app..."
      - name: Run testing script
        run: npm run test
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Signal deployment start
        run: echo "deploying app..."
      - name: Run deployment script
        run: npm run build
